[project]
name = "fastpi01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "ruff>=0.7.3",
]
